version: '3.2'
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "changeit"

  backend:
    image: mtmd/quarkus-backend
    ports:
      - 8080:8080
    environment:
      DB_HOST: postgres
    links:
      - postgres
