---
openapi: 3.0.3
info:
  title: Generated API
  version: "1.0"
servers:
  - url: http://localhost:8080
    description: Default development server
tags:
  - name: V1Ice
    description: Your favorite IceCream API
paths:
  /ice:
    get:
      tags:
        - V1Ice
      summary: Retrieves available ice cream
      operationId: getAllIceCream
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ice'

        "500":
          description: Technical Error. Not your fault.
    post:
      tags:
        - V1Ice
      summary: Add new ice-cream
      operationId: createIce
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Ice'
      responses:
        "201":
          description: Created
        "500":
          description: Technical Error. Not your fault.
  /ice/{name}:
    get:
      tags:
        - V1Ice
      summary: Retrieve ice cream by name
      operationId: getIceByName
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ice'
        "500":
          description: Technical Error. Not your fault.
components:
  schemas:
    Ice:
      type: object
      properties:
        category:
          type: string
        foodIntolerances:
          type: string
        ingredients:
          uniqueItems: true
          type: array
          items:
            type: string
        name:
          type: string
        nutrients:
          format: int32
          type: integer
        purchasePrice:
          type: string
          format: 10 EUR
        retailPrice:
          type: string
          format: 10 EUR
      discriminator:
        propertyName: category
    Water:
      allOf:
        - $ref: '#/components/schemas/Ice'
        - type: object
          required:
            - objectType
          properties:
            flavourAdditive:
              type: array
              items:
                type: string
    Cream:
      allOf:
        - $ref: '#/components/schemas/Ice'
        - type: object
          properties:
            creamInPercent:
              type: integer
    Sorbet:
      allOf:
        - $ref: '#/components/schemas/Ice'
        - type: object
          properties:
            fruitContentInPercent:
              type: integer
            fruits:
              type: array
              items:
                type: string
